<a href="https://colab.research.google.com/github/alberthtan/pandas-numpy/blob/main/Pandas_and_Numpy_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Pandas and Numpy Data Analysis**




**1**: Creating the dataframe from data.

**2:** People who are psychologist or teacher and their number of cars is greater than their family size.

**3:** People who have at most 2 family members and at least 1 car.

**4:** Number of unique jobs in this dataset.





In [2]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [3]:
# import libraries
import numpy as np
import pandas as pd

In [7]:
print("1")
df = pd.DataFrame(data)
print(df)

print("\n2")
df1 = df[((df.job == 'teacher') | (df.job == 'psychologist')) & (df.num_cars > df.family_size)]
print(df1)

print("\n3")
df2 = df[(df.family_size <= 2) & (df.num_cars >= 1)]
print(df2)

print("\n4")
num_unique_jobs = len(set(df['job']))
print("The number of unique jobs is", num_unique_jobs)

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1
   name           job  family_size  num_cars
5  Lisa  psychologist            3         4
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1
The number of unique jobs is 4


**Computing the mean of weights of each fruit.**

In [8]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))     

In [9]:
print(fruit)
print(weights)

mean_apples = np.mean(weights[fruit == 'apple'])
mean_bananas = np.mean(weights[fruit == 'banana'])
mean_carrots = np.mean(weights[fruit == 'carrot'])
print("The mean weight of the apples is", mean_apples)
print("The mean weight of the bananas is", mean_bananas)
print("The mean weight of the carrots is", mean_carrots)

0    carrot
1     apple
2    carrot
3    banana
4    carrot
5    carrot
6     apple
7     apple
8    banana
9     apple
dtype: object
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float64
The mean weight of the apples is 6.75
The mean weight of the bananas is 6.5
The mean weight of the carrots is 3.75



**1**: Getting the indices of the sorted elements of **course_name** array.

**2:** Checking whether each element of **course_name** array starts with "P".


In [10]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [14]:
# Type your solution here

print("1")
print("Original:", course_name)
print("Sorted:", np.sort(course_name))
print("Indices of sorted:", np.argsort(course_name)) # indices of the sorted elements

print("\n2")
check = np.char.find(course_name, 'P') == 0
print("Original:", course_name)
print(check)

Original: ['Python' 'JS' 'examples' 'PHP' 'html']
Sorted: ['JS' 'PHP' 'Python' 'examples' 'html']
Indices of sorted: [1 3 0 2 4]

Original: ['Python' 'JS' 'examples' 'PHP' 'html']
[ True False False  True False]


**1:** Reversing the **student_id** array. 

**2:** Getting the 3-largest values of **student_id** array.

In [12]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [13]:
# Type your solution here
print('1')
reversed = np.flip(student_id)
print("Original Array:", student_id)
print("Reversed Array:", reversed)

print('\n2')
sorted = np.sort(student_id)
print("Three largest numbers:", sorted[:-4:-1])

1
Original Array: [1023 5202 6230 1671 1682 5241 4532]
Reversed Array: [4532 5241 1682 1671 6230 5202 1023]

2
Three largest numbers: [6230 5241 5202]


# Printing the sum of all the multiples of 3 or 5 below 100

In [ ]:
numbers = np.arange(0, 100, 1)

divisible = numbers[(numbers % 3 == 0) | (numbers % 5 == 0)]
print("The sum of all the multiples of 3 or 5 below 100 is", np.sum(divisible)) 

The sum of all the multiples of 3 or 5 below 100 is 2318



1. Swapping column 1 with column 2.

2. Swapping row 0 with row 1.

In [15]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
print('1')
arr[:, [1,2]] = arr[:, [2,1]]
print(arr)

print('\n2')
arr[[0,1], :] = arr[[1,0], :]
print(arr)

1
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]

2
[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
